CREATE TABLE LogTrace (
    TraceID INT AUTO_INCREMENT PRIMARY KEY,
    StartTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    EndTime TIMESTAMP NULL,
    Status VARCHAR(50) DEFAULT 'in-progress'
);

CREATE TABLE Log (
    LogID INT AUTO_INCREMENT PRIMARY KEY,
    TraceID INT,  
    PreviousLogID INT NULL,
    ServiceName VARCHAR(100),
    MethodName VARCHAR(100),
    LogTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Message TEXT,
    Status VARCHAR(50) DEFAULT 'info',
    FOREIGN KEY (TraceID) REFERENCES LogTrace(TraceID),
    FOREIGN KEY (PreviousLogID) REFERENCES Log(LogID)
);